---
- name: Install and start HTTPD
  hosts: all
  become: yes
  tasks:
    - name: Install HTTPD package
      yum:
        name: httpd
        state: absent

    - name: Ensure HTTPD is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
